# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoryAtlasCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_courses', models.CharField(max_length=128)),
                ('grading', models.CharField(max_length=32)),
                ('opus_number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('credit', models.IntegerField()),
                ('notes', models.CharField(max_length=128)),
                ('ger', models.CharField(max_length=32)),
                ('resources', models.TextField()),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=128)),
                ('schedule', models.CharField(max_length=512)),
            ],
        ),
    ]
